version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/public
      - ./src:/usr/src
      - /usr/node_modules # Prevent overwriting node_modules
    environment:
      NODE_ENV: development
